os: linux
dist: xenial
language: python
python: "3.7.1"

matrix:
  include:
    - env: CC=clang-4.0 CXX=clang++-4.0
      addons: { apt: { packages: ["clang-4.0"] } }

    - env: CC=clang-5.0 CXX=clang++-5.0
      addons: { apt: { packages: ["clang-5.0"] } }

    - env: CC=gcc-6 CXX=g++-6
      addons: { apt: { packages: ["gcc-6", "g++-6"], sources: ["ubuntu-toolchain-r-test"] } }

    - env: CC=gcc-7 CXX=g++-7
      addons: { apt: { packages: ["gcc-7", "g++-7"], sources: ["ubuntu-toolchain-r-test"] } }

    - os: osx
      osx_image: xcode8.3
      language: generic
      addons: { homebrew: { packages: ["python3", "cmake"], update: true } }
      cache: { directories: ["$HOME/Library/Caches/Homebrew"] }

    - os: osx
      osx_image: xcode9.1
      language: generic
      addons: { homebrew: { packages: ["python3", "cmake"], update: true } }
      cache: { directories: ["$HOME/Library/Caches/Homebrew"] }

before_install:
  - travis_retry pip3 install conan
  - conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan True

install:
  - travis_retry conan install . --build

script:
  - NODEBUG=1 conan build .
